apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml

# Helm Chart を Kustomize 経由でインストール
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "67.4.0"  # 後日アップグレード検証のため安定版を採用
    releaseName: kube-prometheus
    namespace: monitoring
    valuesFile: values.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: homelab-infra
